version: '3.4'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:11.1
    restart: always
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=test
      - MARIADB_PASSWORD=123456
      - MARIADB_ROOT_PASSWORD=123456
    volumes:
      - ./mariadb:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  mfv2:
    container_name: mfv2
    build:
      context: .
      dockerfile: dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/home/app

